### ISSUE TITLE
Pressing any key while in a backpack crashes the game

### ISSUE THREAD

**Issue by LoganDark** [deletey/compact-storage#64]
Crash report: https://paste.dimdev.org/vafavejego.mccrash

Thanks to VanillaFix for catching this crash. Had it not been caught by VanillaFix, he would have had to restart a Minecraft client with over 200 mods (takes around 30 minutes).

He tells me that pressing any key other than Shift (obvious) crashes the game. (Even Escape)

**Comment by Famous5000** [comment]
That actually happened twice. The first time I can't remember what key I hit. The second time I pressed a mere "W".

**Comment by LoganDark** [comment]
Might be a conflict with MultiHotbars... It only works on his first hotbar.

I don't know what you have going on with the first hotbar, but no other mod has this issue.

**Comment by tobystrong** [comment]
Interesting, i'll look into it
